immortalwrt/luci

- applications/luci-app-jd-dailybonus/luasrc/model/cbi/jd-dailybonus/client.lua
- applications/luci-app-jd-dailybonus/luasrc/view/jd-dailybonus/cookie_tools.htm
> luci-app-jd-dailybonus: no QR code bug fixes

- modules/luci-base/luasrc/model/network.lua
- modules/luci-mod-admin-full/luasrc/model/cbi/admin_network/wifi.lua
- modules/luci-mod-admin-full/luasrc/view/admin_network/wifi_overview.htm
- modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
- modules/luci-mod-admin-full/luasrc/view/cbi/wireless_modefreq.htm
> luci-mod-network: backport 802.11ax HE support

- applications/luci-app-dawn/luasrc/model/cbi/dawn/dawn_config.lua
- applications/luci-app-dawn/po/zh-Hans/dawn.po
> Add luci-app-dawn zh-Hans translations

- applications/luci-app-turboacc/luasrc/view/turboacc/status.htm
Not running shows red, running shows green
> luci-app-turboacc：adapter  luci-theme-openwrt-2020 theme

- applications/luci-app-ssr-plus/luasrc/view/shadowsocksr/status.htm
Not running shows red, running shows green
> luci-app-ssr-plus： adapter luci-theme-openwrt-2020 theme

- applications/luci-app-ssr-plus/root/usr/share/shadowsocksr/subscribe.lua
- 应用/luci-app-ssr-plus/根/我们/共享/暗影袜子/subscribe.lua
> fix some subscribe bugs about grpc and sni

- applications/luci-app-smartdns/htdocs/luci-static/resources/view/smartdns/smartdns.js
refer to smartdns [commit](https://github.com/pymumu/smartdns/commit/c561ae2fc53251d15c114b76f8212eb1afd24ea6) on Apr.29
> Feature: Supports setting the maximum TTL value in Luci

- applications/luci-app-smartdns/htdocs/luci-static/resources/view/smartdns/smartdns.js
Refer to this [commit](https://github.com/pymumu/smartdns/commit/64e5b326cc53df1fec680cfa28ceec5d8a36fcbc)
> sync changes in LuCI to match Release 37.2

- applications/luci-app-smartdns/po/zh_Hans/smartdns.po
Refer to this [commit](https://github.com/pymumu/smartdns/commit/64e5b326cc53df1fec680cfa28ceec5d8a36fcbc)
> sync translation changes in LuCI to match Release 37.2

- applications/luci-app-argon-config/Makefile
fix https://github.com/immortalwrt/immortalwrt/issues/862#issuecomment-1400419436
Signed-off-by: Haris Wu <bymark256@gmail.com>
> luci-app-argon-config: add luci-lib-ipkg interface

- applications/luci-app-kodexplorer/root/etc/init.d/kodexplorer
Signed-off-by: Yu Hua <hue715@gmail.com>
> luci-app-kodexplorer: Fix php8 startup error

- applications/luci-app-baidupcs-web/root/etc/init.d/baidupcs-web
Fixed the problem that the service failed to start
Signed-off-by: Yu Hua <hue715@gmail.com>
> luci-app-baidupcs-web: Fix startup error

- applications/luci-app-passwall/Makefile
- applications/luci-app-passwall/root/etc/hotplug.d/iface/98-passwall
luci: update hotplug.d iface script
> luci-app-passwall: sync with upstream source

- applications/luci-app-passwall/Makefile
- applications/luci-app-passwall/luasrc/controller/passwall.lua
- applications/luci-app-passwall/luasrc/view/passwall/global/status.htm
- applications/luci-app-passwall/root/usr/share/passwall/nftables.sh
> luci-app-passwall: fixup!

- applications/luci-app-passwall/Makefile
- applications/luci-app-passwall/root/usr/share/passwall/app.sh
- applications/luci-app-passwall/root/usr/share/passwall/subscribe.lua
luci: fixed https://github.com/xiaorouji/openwrt-passwall/issues/2493
> luci-app-passwall: bump to 4.64-6

- applications/luci-app-bitsrunlogin-go/htdocs/luci-static/resources/view/bitsrunlogin-go/config.js
- applications/luci-app-bitsrunlogin-go/po/templates/bitsrunlogin-go.pot
- applications/luci-app-bitsrunlogin-go/po/zh_Hans/bitsrunlogin-go.po
Same as https://github.com/immortalwrt/packages/pull/767
> luci-app-bitsrunlogin-go: add new config option 'Auto Detect AC_ID'

- applications/luci-app-passwall/Makefile
- applications/luci-app-passwall/root/usr/share/passwall/subscribe.lua
luci: fix https://github.com/xiaorouji/openwrt-passwall/issues/2735
> luci-app-passwall: bump to 4.69-4

- applications/luci-app-passwall/luasrc/model/cbi/passwall/client/other.lua
- applications/luci-app-passwall/luasrc/model/cbi/passwall/client/type/ray.lua
- applications/luci-app-passwall/luasrc/passwall/util_xray.lua
- applications/luci-app-passwall/po/zh_Hans/passwall.po
https://github.com/xiaorouji/openwrt-passwall/compare/ab7e0885c6072401c264a4d2a84977c2dbd7fe70...6474ec22c0f6cebfd0be57186bbf6776d22a9bfe
> luci-app-passwall: sync upstream

- applications/luci-app-dockerman/luasrc/model/cbi/dockerman/containers.lua
- applications/luci-app-dockerman/luasrc/model/cbi/dockerman/networks.lua
https://github.com/coolsnowwolf/luci/pull/270
> luci-app-dockerman: fix network page issue

- applications/luci-app-ddns-go/htdocs/luci-static/resources/view/ddns-go.js
- applications/luci-app-ddns-go/po/templates/ddns-go.pot
- applications/luci-app-ddns-go/po/zh_Hans/ddns-go.po
- applications/luci-app-ddns-go/po/zh_Hant/ddns-go.po
luci-app-ddns-go: add dns option
> luci-app-ddns-go: add dns option

- applications/luci-app-passwall/Makefile
- applications/luci-app-passwall/luasrc/model/cbi/passwall/client/shunt_rules.lua
- applications/luci-app-passwall/luasrc/passwall/util_xray.lua
- applications/luci-app-passwall/root/usr/share/passwall/app.sh
- applications/luci-app-passwall/root/usr/share/passwall/helper_chinadns_add.lua
- applications/luci-app-passwall/root/usr/share/passwall/helper_smartdns_add.lua
luci-app-passwall: fix https://github.com/xiaorouji/openwrt-passwall/issues/3719
luci-app-passwall: add source port in shunt rules
luci-app-passwall: optimize geo data parsing logs
> luci-app-passwall: bump to 25.2.12

- applications/luci-app-dufs/htdocs/luci-static/resources/view/dufs.js
- applications/luci-app-dufs/po/templates/dufs.pot
- applications/luci-app-dufs/po/zh_Hans/dufs.po
After this change, `Open Web Interface` works as expected when `path_prefix` is set.
> luci-app-dufs: support (URL) path_prefix

- applications/luci-app-passwall/Makefile
- applications/luci-app-passwall/luasrc/controller/passwall.lua
- applications/luci-app-passwall/luasrc/model/cbi/passwall/client/global.lua
- applications/luci-app-passwall/luasrc/model/cbi/passwall/client/node_list.lua
- applications/luci-app-passwall/luasrc/model/cbi/passwall/client/other.lua
- applications/luci-app-passwall/luasrc/model/cbi/passwall/client/rule.lua
- applications/luci-app-passwall/luasrc/model/cbi/passwall/client/type/sing-box.lua
- applications/luci-app-passwall/luasrc/passwall/api.lua
- applications/luci-app-passwall/luasrc/passwall/com.lua
- applications/luci-app-passwall/luasrc/passwall/util_sing-box.lua
- applications/luci-app-passwall/po/zh_Hans/passwall.po
- applications/luci-app-passwall/root/usr/share/passwall/0_default_config
- applications/luci-app-passwall/root/usr/share/passwall/app.sh
- applications/luci-app-passwall/root/usr/share/passwall/helper_chinadns_add.lua
- applications/luci-app-passwall/root/usr/share/passwall/helper_smartdns_add.lua
- applications/luci-app-passwall/root/usr/share/passwall/rule_update.lua
- applications/luci-app-passwall/root/usr/share/passwall/subscribe.lua
- applications/luci-app-passwall/root/usr/share/passwall/test.sh
luci-app-passwall: optimize connect test
luci-app-passwall: optimize PW version number retrieval
luci-app-passwall: optimize connect test
luci-app-passwall: app_update add chinadns-ng riscv64 arch
luci-app-passwall: optimize
luci-app-passwall: update the steam game platform diversion rules to implement proxy traffic except for game downloads
luci-app-passwall: support sing-box urltest
luci-app-passwall: optimize rule_update
luci-app-passwall: expand ipt2socks nofile limit
> luci-app-passwall: update to 23.3.2

- applications/luci-app-argon-config/htdocs/luci-static/resources/view/argon-config.js
- applications/luci-app-argon-config/po/templates/argon-config.pot
- applications/luci-app-argon-config/po/zh_Hans/argon-config.po
Add setting support for collection_id and resolutions tag in argon-config
> luci-app-argon-config: sync setting flag for online_wallpaper
